<?php

namespace DonBundle\Repository;

/**
 * DonEspeceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonEspeceRepository extends \Doctrine\ORM\EntityRepository
{
}
