<?php

namespace DonBundle\Repository;

/**
 * DonNatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonNatureRepository extends \Doctrine\ORM\EntityRepository
{
}
