<?php

namespace AideBundle\Repository;

/**
 * AideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AideRepository extends \Doctrine\ORM\EntityRepository
{
    public function approuver($id,$status){
        $query = $this->getEntityManager()
            ->createQuery(" UPDATE AideBundle:Aide a SET a.statutAide=:avis where a.id=:id ")
            ->setParameter('id', $id)
            ->setParameter('avis', $status);
        return $query->getResult();
    }
    public function consulter($id){
        $query = $this->getEntityManager()
            ->createQuery(" SELECT * AideBundle:Aide a where a.user=:id ")
            ->setParameter('id', $id);
        return $query->getResult();
    }


}
