<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container3jvqjnr\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container3jvqjnr/appProdProjectContainer.php') {
    touch(__DIR__.'/Container3jvqjnr.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container3jvqjnr\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container3jvqjnr\appProdProjectContainer([
    'container.build_hash' => '3jvqjnr',
    'container.build_id' => '003a9835',
    'container.build_time' => 1585661126,
], __DIR__.\DIRECTORY_SEPARATOR.'Container3jvqjnr');
