<?php

namespace BlogBundle\Repository;

/**
 * CommentaireArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireArticleRepository extends \Doctrine\ORM\EntityRepository
{
}
