<?php

namespace EvenementBundle\Repository;

/**
 * EvenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUser($id)
    {
        $query= $this->getEntityManager()
                     ->createQuery(" SELECT e.evenementId,e.title,e.lieuEvenement,e.prixEvenement,e.start,e.end,e.porteeEvenement,e.image FROM EvenementBundle:Evenement e where e.user=:id")
                     ->setParameter('id', $id);
        return $query->getResult();
    }
   
}

