<?php

namespace EvenementBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParticipants($evenementId)
    {
     
      
        $query =$this->getEntityManager()
                     ->createQuery("SELECT u.username
                      FROM UserBundle:User u 
                      WHERE( 
                             u.id 
                            IN 
                            ( 
                                SELECT IDENTIFY p.user from EvenementBundle\Entity\Participation p 
                               where (p.events=:evenementId)
                            )
                            ) 
                               ") 
                     ->setParameter('evenementId', $evenementId);
         return $query->getResult();
    }
}
