<?php

namespace EvenementBundle\Repository;

/**
 * ParticipationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findParticipants($evenementId)
    {
        $query= $this->getEntityManager()
        ->createQuery(" SELECT u.username FROM UserBundle:User u, EvenementBundle:Evenement e, EvenementBundle:Participation p where e.evenementId=:evenementId and p.user=u.id and p.events=e.evenementId ")
        ->setParameter('evenementId', $evenementId);
return $query->getResult();
      

    }
   
}
